name: SellMe
author: cosmicnebula200
api: 4.0.0
main: cosmicnebula200\SellMe\SellMe
version: 1.0.0
softdepend: ['BedrockEconomy', 'Capital', 'EconomyAPI']

permissions:
  sellme.command.sell.hand:
    default: true
    description: with this permission the player sell his/her hand
  sellme.command.sell.all:
    default: true
    description: with this permission the player sell all items in his/her inv which are similar to his current item in hand
  sellme.command.sell.inv:
    default: true
    description: with this permission the player can sell his/her inventory
  sellme.command.sell.list:
    default: true
    description: with this permission the player can view sell listing
  sellme.command.autosell:
    default: true
    description: with this permission the player can toggle his autosell status