name: SellMe
author: cosmicnebula200
api: 4.0.0
main: cosmicnebula200\SellMe\SellMe
version: 2.0.1
softdepend: ['BedrockEconomy']

permissions:
  sellme.command.sell.hand:
    default: true
    description: with this permission the player sell his/her hand
  sellme.command.sell.all:
    default: true
    description: with this permission the player sell all items in his/her inv which are similar to his current item in hand
  sellme.command.sell.inv:
    default: true
    description: with this permission the player can sell his/her inventory
  sellme.command.sell.list:
    default: true
    description: with this permission the player can view sell listing
  sellme.command.sell.add:
    default: op
    description: with this permission the player can add items to the sell prices
  sellme.command.sell.overwrite:
    default: op
    description: with this permission the player can overwrite the prices of the items from the list of prices
  sellme.command.sell.check:
    default: true
    description: with this permission the player can view the price of the items in their inventory
  sellme.command.autosell:
    default: true
    description: with this permission the player can toggle his autosell status