# config for SellMe by cosmicnebula200

# Economy provider
# the possible values for this currently are
# 1. BedrockEconomy
# If more Economy providers are added for PocketMine 5 then I will update it
economy-provider: BedrockEconomy